//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignManager.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alignment
    {
        public Alignment()
        {
            this.Characters = new HashSet<Character>();
            this.AlignmentsCharacterClasses = new HashSet<AlignmentsCharacterClass>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<AlignmentsCharacterClass> AlignmentsCharacterClasses { get; set; }
    }
}
