//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignManager.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterClass
    {
        public CharacterClass()
        {
            this.AlignmentsCharacterClasses = new HashSet<AlignmentsCharacterClass>();
            this.ClassSkills = new HashSet<ClassSkill>();
            this.SpellLevels = new HashSet<SpellLevel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string Type { get; set; }
        public int HitDie { get; set; }
        public int SkillPoints { get; set; }
        public string AttackBonusType { get; set; }
        public string FortitudeType { get; set; }
        public string ReflexType { get; set; }
        public string WillpowerType { get; set; }
        public string Source { get; set; }
        public bool Hidden { get; set; }
    
        public virtual ICollection<AlignmentsCharacterClass> AlignmentsCharacterClasses { get; set; }
        public virtual ICollection<ClassSkill> ClassSkills { get; set; }
        public virtual ICollection<SpellLevel> SpellLevels { get; set; }
    }
}
