//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignManager.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public Spell()
        {
            this.SpellLevels = new HashSet<SpellLevel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string School { get; set; }
        public string SubSchool { get; set; }
        public string Descriptor { get; set; }
        public string CastingTime { get; set; }
        public string Components { get; set; }
        public string Range { get; set; }
        public string Area { get; set; }
        public string Effect { get; set; }
        public string Targets { get; set; }
        public string Duration { get; set; }
        public string SavingThrow { get; set; }
        public string SpellResistance { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string DescriptionFormatted { get; set; }
        public string Source { get; set; }
        public bool Hidden { get; set; }
    
        public virtual ICollection<SpellLevel> SpellLevels { get; set; }
    }
}
